stages:
  - build
  - test-backend
  - test-frontend

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - cd frontend
    - npm install
    - npm run build
    - echo "Build successfully!"

test-backend:
  stage: test-backend
  image: python3
  script:
    - echo "Testing backend"
    - cd backend
    - pip install -r requirements.txt
    - python tests.py

test-frontend:
  stage: test-frontend
  image: node
  script:
    - echo "Testing frontend"
    - cd frontend
    - npm install
    - npm run build
    - npm run test-ci
    - echo "Test successfully!"