stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - cd app
    - npm install
    - npm run build
    - echo "Build successfully!"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - cd app
    - npm install
    - npm run build
    - npm run test-ci
    - echo "Test successfully!"